/*
 * ToDo API
 *
 * An ASP.NET Core Web API for managing ToDo items
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using ExampleApi.Client.Api;
using ExampleApi.Client.Model;
using ExampleApi.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace ExampleApi.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TodoItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TodoItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TodoItem
        //private TodoItem instance;

        public TodoItemTests()
        {
            // TODO uncomment below to create an instance of TodoItem
            //instance = new TodoItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TodoItem
        /// </summary>
        [Fact]
        public void TodoItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" TodoItem
            //Assert.IsType<TodoItem>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'IsComplete'
        /// </summary>
        [Fact]
        public void IsCompleteTest()
        {
            // TODO unit test for the property 'IsComplete'
        }

    }

}
