name: build-publish

on:
  push:
    tags: 'v*'

env:
  DOTNET_VERSION: '7.0.100' # The .NET SDK version to use

jobs:
  build-publish:
    runs-on: ubuntu-latest
    name: build-publish
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest

    - name: Add NuGet source
      run: dotnet nuget update source github -u github -p ${{ secrets.PAT }} --store-password-in-clear-text

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Install tools
      run: dotnet tool restore

    - name: Install dependencies
      run: dotnet restore src/*.Client/*.csproj

    - name: Build
      run: dotnet build --configuration Release --no-restore src/*.Client/*.csproj

    - name: Test
      run: |
        dotnet restore src/*.Client.Test/*.csproj
        dotnet build --configuration Release --verbosity d --no-restore src/*.Client.Test/*.csproj
        dotnet test --configuration Release --verbosity d --no-build src/*.Client.Test/*.csproj

    - name: Publish
      run: dotnet pack --configuration Release src/*.Client/*.csproj

    - name: Publish
      run: dotnet nuget push ./src/ExampleApi.Client/bin/Release/*.nupkg --source github
